#!/bin/bash

# https://moma.corp.google.com/person/rishisinghal
# 02/05/2020
# see also
# cost optimization for GCP
# https://docs.google.com/presentation/d/1m0ahmrEJpoC-GDRoKVL_AC56hGALn6RAupwMzyY-Jm0/edit#slide=id.g3bec517c07_32_433

for project in  $(gcloud projects list --format="value(projectId)")
do
  echo "ProjectId:  $project"
	for zone in  $(gcloud compute zones list --format="value(name)")
	do
  	# echo "Zone:  $zone"
		gcloud beta recommender recommendations list \
    	--project $project \
    	--location $zone \
    	--recommender=google.compute.instance.MachineTypeRecommender \
 		--format="csv[no-heading](description:label='Action',primaryImpact.costProjection.cost.units:label='Projected 		Cost',primaryImpact.costProjection.cost.currencyCode:label='Currency', content.operationGroups.operations.resource)"
	done
done
